# Generated by Django 2.1.1 on 2018-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=60)),
                ('version', models.CharField(max_length=60)),
                ('services', models.CharField(max_length=60)),
                ('user_agent', models.CharField(max_length=60)),
                ('start_height', models.CharField(max_length=60)),
            ],
        ),
    ]
