# Generated by Django 2.1.1 on 2018-10-26 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('btccrawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
