# Generated by Django 2.1.1 on 2018-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btccrawl', '0002_auto_20181026_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.CharField(max_length=60),
        ),
    ]
